import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import type { Metadata } from "next";
import { Footer, GoogleAnalytics, Header } from "@/components";
import theme from "./theme/themes";
import "./globals.css";

export const metadata: Metadata = {
  title: "EDA - Eletricidade dos Açores",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh",
          }}
        >
          <Header />
          <Box sx={{ flex: 1, marginTop: { xs: "60px", lg: "108px" } }}>
            {children}
          </Box>
          <Footer />
          <GoogleAnalytics />
        </body>
        <script
          id="Cookiebot"
          src="https://consent.cookiebot.com/uc.js"
          data-cbid="9548ed4d-0bd1-4d04-a0f9-e8d14d5d1c28"
          type="text/javascript"
          async
        ></script>
        <script
          id="CookieDeclaration"
          src="https://consent.cookiebot.com/9548ed4d-0bd1-4d04-a0f9-e8d14d5d1c28/cd.js"
          type="text/javascript"
          async
        ></script>
      </ThemeProvider>
    </html>
  );
}
